- hosts: localhost
  become: true
  pre_tasks: 
    - name: update repositories
      apt: update_cache=yes
      changed_when: false

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/google_chrome.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/pyenv.yml