- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - net-tools
    - htop
    - neofetch
    - fzf
    - tmux
    - xclip
    - trash-cli
    - python3.11-venv
    
- name: Install snap packages
  snap:
    name:
      - dirsize
      - netron
      - postman

- name: Install vscode
  snap:
    name: code
    classic: true