- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev
    - curl
    - htop
    - neofetch
    - fzf
    - tmux
    - xclip
    - trash-cli
    - python3.11-venv
    
- name: Install snap packages
  snap:
    name:
      - dirsize
      - netron
      - postman

- name: Install vscode
  snap:
    name: code
    classic: true