- name: Set gnome dock settings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "48" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-position", value: "'BOTTOM'" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/extend-height", value: "false" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/show-trash", value: "false" }
  become_user: pablo

- name: Don't show home folder on desktop
  dconf:
    key: "/org/gnome/shell/extensions/ding/show-home"
    value: "false"
  become_user: pablo

- name: Set gnome background
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/desktop/background/color-shading-type", value: "'solid'" }
    - { key: "/org/gnome/desktop/background/picture-options", value: "'zoom'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/Milkyway_by_mizuno_as.png'" }
    - { key: "/org/gnome/desktop/background/picture-uri-dark", value: "'file:///usr/share/backgrounds/Milkyway_by_mizuno_as.png'" }
    - { key: "/org/gnome/desktop/background/primary-color", value: "'#000000'" }
    - { key: "/org/gnome/desktop/background/secondary-color", value: "'#000000'" }
  become_user: pablo

- name: Configure available keyboard layouts in Gnome
  dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'us'), ('xkb', 'latam')]"
  become_user: pablo

- name: Configure image viewer
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/eog/ui/image-gallery", value: "false" }
    - { key: "/org/gnome/eog/ui/sidebar", value: "true" }
    - { key: "/org/gnome/eog/ui/statusbar", value: "true" }
  become_user: pablo

- name: Configure workspace keybindings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-last", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-last", value: "@as []" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up", value: "@as []" }
  become_user: pablo

- name: Configure nautilus
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/nautilus/compression/default-compression-format", value: "'zip'" }
  become_user: pablo

- name: Configure terminal mode and keybindings
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/terminal/legacy/new-terminal-mode", value: "'tab'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/close-tab", value: "'<Primary>w'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/close-window", value: "'<Primary>q'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/find", value: "'<Primary>f'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/find-clear", value: "'<Primary>j'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/find-next", value: "'<Primary>g'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/find-previous", value: "'<Primary>h'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/move-tab-left", value: "'<Primary>Right'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/move-tab-right", value: "'<Primary>Left'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/new-tab", value: "'<Primary>t'" }
    - { key: "/org/gnome/terminal/legacy/keybindings/new-window", value: "'<Primary>n'" }
  become_user: pablo

- name: Configure terminal style
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color", value: "'rgb(14,12,24)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent", value: "0" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/bold-is-bright", value: "true" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-columns", value: "160" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/default-size-rows", value: "24" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font", value: "'Monospace 11'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(208,207,204)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/pallete", value: "['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(30,79,141)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(91,150,221)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(208,207,204)'" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-trasnparency", value: "false" }
    - { key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color", value: "'rgb(208,207,204)'" }
  become_user: pablo
- name: Configure dock apps
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['firefox_firefox.desktop', 'thunderbird.desktop', 'org.gnome.Nautilus.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop', 'postman_postman.desktop', 'google-chrome.desktop']"
  become_user: pablo

